name: example
description: flutter_html example app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_html_fix:
    path: ../
  flutter_html_all:
    path: ../packages/flutter_html_all
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  flutter_html_all:
    path: ../packages/flutter_html_all

flutter:

  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg