name: flutter_html_fix
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 3.0.1
homepage: https://github.com/The28AWG/flutter_html_fix
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=2.2.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.4

  # Plugin for parsing css
  csslib: ^1.0.0

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.19.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  meta: ^1.15.0
  melos: ^6.1.0

dependency_overrides:
  collection: ^1.19.0

screenshots:
  - description: 'An example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot1.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot2.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot3.png
  - description: 'Another example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_readme_screenshot.png 

topics:
  - html
  - css
  - widgets
  - layout
  - flutter_html
