name: flutter_html_audio
description: This extension package allows the <audio> tag to be rendered using the flutter_html package
version: 3.0.1
homepage: https://github.com/The28AWG/flutter_html_fix
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html_fix:
    git: https://github.com/The28AWG/flutter_html_fix.git
  video_player: '>=2.2.8 <3.0.0'
  chewie_audio: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  flutter_html_fix:
    path: ../../

topics:
  - html
  - css
  - audio
  - layout
  - flutter_html_fix
