name: flutter_html_table
description: This extension package allows the <table> tag to be rendered using the flutter_html package
version: 3.0.1
homepage: https://github.com/The28AWG/flutter_html_fix
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html_fix:
    git: https://github.com/The28AWG/flutter_html_fix.git
  flutter_layout_grid: '>=1.0.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  flutter_html_fix:
    path: ../../

topics:
  - html
  - css
  - table
  - layout
  - flutter_html_fix
